# Generated by Django 5.2.7 on 2025-11-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pptdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('object', models.TextField()),
                ('timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pptdata',
            },
        ),
    ]
